/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Topics = IDL.Variant({
  'businessPartnerships' : IDL.Null,
  'interviewRequests' : IDL.Null,
  'publishingSubmissions' : IDL.Null,
  'eventOrWorkshopProposals' : IDL.Null,
  'advertisingInquiries' : IDL.Null,
  'challengesAndBounties' : IDL.Null,
  'generalInquiries' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactRequest = IDL.Record({
  'id' : IDL.Text,
  'topic' : Topics,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'processed' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const NewRequest = IDL.Record({
  'topic' : Topics,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRequestsByStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getRequestsByTopic' : IDL.Func(
      [Topics],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func([NewRequest], [IDL.Text], []),
  'updateRequestStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Topics = IDL.Variant({
    'businessPartnerships' : IDL.Null,
    'interviewRequests' : IDL.Null,
    'publishingSubmissions' : IDL.Null,
    'eventOrWorkshopProposals' : IDL.Null,
    'advertisingInquiries' : IDL.Null,
    'challengesAndBounties' : IDL.Null,
    'generalInquiries' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactRequest = IDL.Record({
    'id' : IDL.Text,
    'topic' : Topics,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'processed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const NewRequest = IDL.Record({
    'topic' : Topics,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRequestsByStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getRequestsByTopic' : IDL.Func(
        [Topics],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func([NewRequest], [IDL.Text], []),
    'updateRequestStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };