/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : string,
  'bio' : string,
  'displayOrder' : bigint,
  'traits' : Array<string>,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
  'power' : string,
  'weapon' : string,
}
export interface Clan {
  'name' : string,
  'description' : string,
  'uniqueAbilities' : Array<string>,
  'notableMembers' : Array<string>,
  'symbol' : string,
}
export interface ClanEyeRule { 'description' : string, 'symbol' : string }
export interface ContactRequest {
  'id' : string,
  'topic' : Topics,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'processed' : boolean,
}
export interface Content {
  'id' : string,
  'title' : string,
  'contentType' : string,
  'body' : string,
  'imageUrl' : [] | [string],
}
export interface Episode {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export interface NewCharacter {
  'bio' : string,
  'traits' : Array<string>,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
  'power' : string,
  'weapon' : string,
}
export interface NewContent {
  'title' : string,
  'contentType' : string,
  'body' : string,
  'imageUrl' : [] | [string],
}
export interface NewEpisode {
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export interface NewReferral { 'source' : string, 'otherText' : [] | [string] }
export interface NewRequest {
  'topic' : Topics,
  'email' : string,
  'message' : string,
}
export interface PowerSystemElement {
  'categories' : Array<string>,
  'name' : string,
  'description' : string,
  'masteryLevels' : Array<string>,
  'symbol' : string,
}
export interface Rank {
  'title' : string,
  'privileges' : Array<string>,
  'responsibilities' : Array<string>,
  'rankingRequirements' : Array<string>,
  'order' : bigint,
  'description' : string,
  'symbol' : string,
}
export interface ReferralSource {
  'id' : string,
  'source' : string,
  'otherText' : [] | [string],
  'timestamp' : Time,
}
export interface ShiranagiFamily {
  'symbols' : Array<string>,
  'bloodlinePowers' : Array<string>,
  'coreEthos' : string,
  'history' : string,
  'affiliations' : Array<string>,
  'notableMembers' : Array<string>,
  'familyValues' : Array<string>,
  'evolutionOverTime' : string,
}
export type Time = bigint;
export type Topics = { 'businessPartnerships' : null } |
  { 'interviewRequests' : null } |
  { 'publishingSubmissions' : null } |
  { 'eventOrWorkshopProposals' : null } |
  { 'advertisingInquiries' : null } |
  { 'challengesAndBounties' : null } |
  { 'generalInquiries' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Worldbuilding {
  'powerSystem' : Array<PowerSystemElement>,
  'clanEyeRules' : Array<ClanEyeRule>,
  'clans' : Array<Clan>,
  'shiranagiFamily' : ShiranagiFamily,
  'rankSystem' : Array<Rank>,
}
export interface _SERVICE {
  'addCharacter' : ActorMethod<[NewCharacter], Character>,
  'addContent' : ActorMethod<[NewContent], Content>,
  'addEpisode' : ActorMethod<[NewEpisode], Episode>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCharacter' : ActorMethod<[string], undefined>,
  'deleteContactRequest' : ActorMethod<[string], undefined>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'deleteEpisode' : ActorMethod<[string], undefined>,
  'deleteReferral' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCharacterById' : ActorMethod<[string], [] | [Character]>,
  'getCharacterImage' : ActorMethod<[string], [] | [string]>,
  'getCharacters' : ActorMethod<[], Array<Character>>,
  'getCharactersMetadata' : ActorMethod<[], Array<Character>>,
  'getContactRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getContentById' : ActorMethod<[string], [] | [Content]>,
  'getEpisodes' : ActorMethod<[], Array<Episode>>,
  'getMyRole' : ActorMethod<[], string>,
  'getReferrals' : ActorMethod<[], Array<ReferralSource>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorldbuilding' : ActorMethod<[], [] | [Worldbuilding]>,
  'initialize' : ActorMethod<[], undefined>,
  'markContactRequestProcessed' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCharacterOrder' : ActorMethod<[Array<string>], undefined>,
  'setWorldbuilding' : ActorMethod<[Worldbuilding], undefined>,
  'submitContactRequest' : ActorMethod<[NewRequest], ContactRequest>,
  'submitReferral' : ActorMethod<[NewReferral], ReferralSource>,
  'updateCharacter' : ActorMethod<[string, NewCharacter], [] | [Character]>,
  'updateContent' : ActorMethod<[string, NewContent], [] | [Content]>,
  'updateEpisode' : ActorMethod<[string, NewEpisode], [] | [Episode]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];