/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Rank {
    title: string;
    privileges: Array<string>;
    responsibilities: Array<string>;
    rankingRequirements: Array<string>;
    order: bigint;
    description: string;
    symbol: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Content {
    id: string;
    title: string;
    contentType: string;
    body: string;
    imageUrl?: string;
}
export interface NewCharacter {
    bio: string;
    traits: Array<string>;
    name: string;
    role: string;
    imageUrl: string;
    power: string;
    weapon: string;
}
export interface ShiranagiFamily {
    symbols: Array<string>;
    bloodlinePowers: Array<string>;
    coreEthos: string;
    history: string;
    affiliations: Array<string>;
    notableMembers: Array<string>;
    familyValues: Array<string>;
    evolutionOverTime: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PowerSystemElement {
    categories: Array<string>;
    name: string;
    description: string;
    masteryLevels: Array<string>;
    symbol: string;
}
export interface Character {
    id: string;
    bio: string;
    displayOrder: bigint;
    traits: Array<string>;
    name: string;
    role: string;
    imageUrl: string;
    power: string;
    weapon: string;
}
export interface Episode {
    id: string;
    title: string;
    thumbnailUrl: string;
    description: string;
    seasonNumber: bigint;
    episodeNumber: bigint;
    videoUrl: string;
}
export interface NewRequest {
    topic: Topics;
    email: string;
    message: string;
}
export interface ContactRequest {
    id: string;
    topic: Topics;
    email: string;
    message: string;
    timestamp: Time;
    processed: boolean;
}
export interface NewContent {
    title: string;
    contentType: string;
    body: string;
    imageUrl?: string;
}
export interface ClanEyeRule {
    description: string;
    symbol: string;
}
export interface Clan {
    name: string;
    description: string;
    uniqueAbilities: Array<string>;
    notableMembers: Array<string>;
    symbol: string;
}
export interface Worldbuilding {
    powerSystem: Array<PowerSystemElement>;
    clanEyeRules: Array<ClanEyeRule>;
    clans: Array<Clan>;
    shiranagiFamily: ShiranagiFamily;
    rankSystem: Array<Rank>;
}
export interface NewEpisode {
    title: string;
    thumbnailUrl: string;
    description: string;
    seasonNumber: bigint;
    episodeNumber: bigint;
    videoUrl: string;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Topics {
    businessPartnerships = "businessPartnerships",
    interviewRequests = "interviewRequests",
    publishingSubmissions = "publishingSubmissions",
    eventOrWorkshopProposals = "eventOrWorkshopProposals",
    advertisingInquiries = "advertisingInquiries",
    challengesAndBounties = "challengesAndBounties",
    generalInquiries = "generalInquiries"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCharacter(newChar: NewCharacter): Promise<Character>;
    addContent(newContent: NewContent): Promise<Content>;
    addEpisode(newEp: NewEpisode): Promise<Episode>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCharacter(id: string): Promise<void>;
    deleteContent(id: string): Promise<void>;
    deleteEpisode(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacters(): Promise<Array<Character>>;
    getContactRequests(): Promise<Array<ContactRequest>>;
    getContentById(id: string): Promise<Content | null>;
    getEpisodes(): Promise<Array<Episode>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorldbuilding(): Promise<Worldbuilding | null>;
    isCallerAdmin(): Promise<boolean>;
    markContactRequestProcessed(id: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCharacterOrder(orderedIds: Array<string>): Promise<void>;
    setWorldbuilding(worldbuildingData: Worldbuilding): Promise<void>;
    submitContactRequest(request: NewRequest): Promise<ContactRequest>;
    updateCharacter(id: string, updatedChar: NewCharacter): Promise<Character | null>;
    updateContent(id: string, updatedContent: NewContent): Promise<Content | null>;
    updateEpisode(id: string, updatedEp: NewEpisode): Promise<Episode | null>;
}
import type { Character as _Character, ContactRequest as _ContactRequest, Content as _Content, Episode as _Episode, NewContent as _NewContent, NewRequest as _NewRequest, Time as _Time, Topics as _Topics, UserProfile as _UserProfile, UserRole as _UserRole, Worldbuilding as _Worldbuilding, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCharacter(arg0: NewCharacter): Promise<Character> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharacter(arg0);
            return result;
        }
    }
    async addContent(arg0: NewContent): Promise<Content> {
        if (this.processError) {
            try {
                const result = await this.actor.addContent(to_candid_NewContent_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Content_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContent(to_candid_NewContent_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Content_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addEpisode(arg0: NewEpisode): Promise<Episode> {
        if (this.processError) {
            try {
                const result = await this.actor.addEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEpisode(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCharacter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacter(arg0);
            return result;
        }
    }
    async deleteContent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContent(arg0);
            return result;
        }
    }
    async deleteEpisode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEpisode(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacters(): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacters();
            return result;
        }
    }
    async getContactRequests(): Promise<Array<ContactRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactRequests();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactRequests();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentById(arg0: string): Promise<Content | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentById(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentById(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisodes(): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodes();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorldbuilding(): Promise<Worldbuilding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorldbuilding();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorldbuilding();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markContactRequestProcessed(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactRequestProcessed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactRequestProcessed(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCharacterOrder(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCharacterOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCharacterOrder(arg0);
            return result;
        }
    }
    async setWorldbuilding(arg0: Worldbuilding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWorldbuilding(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWorldbuilding(arg0);
            return result;
        }
    }
    async submitContactRequest(arg0: NewRequest): Promise<ContactRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactRequest(to_candid_NewRequest_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ContactRequest_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactRequest(to_candid_NewRequest_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ContactRequest_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCharacter(arg0: string, arg1: NewCharacter): Promise<Character | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacter(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacter(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContent(arg0: string, arg1: NewContent): Promise<Content | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, to_candid_NewContent_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, to_candid_NewContent_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEpisode(arg0: string, arg1: NewEpisode): Promise<Episode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEpisode(arg0, arg1);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEpisode(arg0, arg1);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContactRequest_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactRequest): ContactRequest {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Content_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Content): Content {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Topics_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topics): Topics {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Content]): Content | null {
    return value.length === 0 ? null : from_candid_Content_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Worldbuilding]): Worldbuilding | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Character]): Character | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Episode]): Episode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    contentType: string;
    body: string;
    imageUrl: [] | [string];
}): {
    id: string;
    title: string;
    contentType: string;
    body: string;
    imageUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        contentType: value.contentType,
        body: value.body,
        imageUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.imageUrl))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: _Topics;
    email: string;
    message: string;
    timestamp: _Time;
    processed: boolean;
}): {
    id: string;
    topic: Topics;
    email: string;
    message: string;
    timestamp: Time;
    processed: boolean;
} {
    return {
        id: value.id,
        topic: from_candid_Topics_n23(_uploadFile, _downloadFile, value.topic),
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        processed: value.processed
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessPartnerships: null;
} | {
    interviewRequests: null;
} | {
    publishingSubmissions: null;
} | {
    eventOrWorkshopProposals: null;
} | {
    advertisingInquiries: null;
} | {
    challengesAndBounties: null;
} | {
    generalInquiries: null;
}): Topics {
    return "businessPartnerships" in value ? Topics.businessPartnerships : "interviewRequests" in value ? Topics.interviewRequests : "publishingSubmissions" in value ? Topics.publishingSubmissions : "eventOrWorkshopProposals" in value ? Topics.eventOrWorkshopProposals : "advertisingInquiries" in value ? Topics.advertisingInquiries : "challengesAndBounties" in value ? Topics.challengesAndBounties : "generalInquiries" in value ? Topics.generalInquiries : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactRequest>): Array<ContactRequest> {
    return value.map((x)=>from_candid_ContactRequest_n21(_uploadFile, _downloadFile, x));
}
function to_candid_NewContent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewContent): _NewContent {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_NewRequest_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewRequest): _NewRequest {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Topics_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topics): _Topics {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: Topics;
    email: string;
    message: string;
}): {
    topic: _Topics;
    email: string;
    message: string;
} {
    return {
        topic: to_candid_Topics_n31(_uploadFile, _downloadFile, value.topic),
        email: value.email,
        message: value.message
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contentType: string;
    body: string;
    imageUrl?: string;
}): {
    title: string;
    contentType: string;
    body: string;
    imageUrl: [] | [string];
} {
    return {
        title: value.title,
        contentType: value.contentType,
        body: value.body,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none()
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Topics): {
    businessPartnerships: null;
} | {
    interviewRequests: null;
} | {
    publishingSubmissions: null;
} | {
    eventOrWorkshopProposals: null;
} | {
    advertisingInquiries: null;
} | {
    challengesAndBounties: null;
} | {
    generalInquiries: null;
} {
    return value == Topics.businessPartnerships ? {
        businessPartnerships: null
    } : value == Topics.interviewRequests ? {
        interviewRequests: null
    } : value == Topics.publishingSubmissions ? {
        publishingSubmissions: null
    } : value == Topics.eventOrWorkshopProposals ? {
        eventOrWorkshopProposals: null
    } : value == Topics.advertisingInquiries ? {
        advertisingInquiries: null
    } : value == Topics.challengesAndBounties ? {
        challengesAndBounties: null
    } : value == Topics.generalInquiries ? {
        generalInquiries: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
