/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : string,
  'bio' : string,
  'traits' : Array<string>,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
  'power' : string,
  'weapon' : string,
}
export interface ContactRequest {
  'id' : string,
  'topic' : Topics,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'processed' : boolean,
}
export interface Content {
  'id' : string,
  'title' : string,
  'contentType' : string,
  'body' : string,
  'imageUrl' : [] | [string],
}
export interface Episode {
  'id' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export interface NewCharacter {
  'bio' : string,
  'traits' : Array<string>,
  'name' : string,
  'role' : string,
  'imageUrl' : string,
  'power' : string,
  'weapon' : string,
}
export interface NewContent {
  'title' : string,
  'contentType' : string,
  'body' : string,
  'imageUrl' : [] | [string],
}
export interface NewEpisode {
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
  'videoUrl' : string,
}
export interface NewRequest {
  'topic' : Topics,
  'email' : string,
  'message' : string,
}
export type Time = bigint;
export type Topics = { 'businessPartnerships' : null } |
  { 'interviewRequests' : null } |
  { 'publishingSubmissions' : null } |
  { 'eventOrWorkshopProposals' : null } |
  { 'advertisingInquiries' : null } |
  { 'challengesAndBounties' : null } |
  { 'generalInquiries' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<[NewCharacter], string>,
  'createContent' : ActorMethod<[NewContent], string>,
  'createEpisode' : ActorMethod<[NewEpisode], string>,
  'deleteCharacter' : ActorMethod<[string], undefined>,
  'deleteContactRequest' : ActorMethod<[string], undefined>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'deleteEpisode' : ActorMethod<[string], undefined>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllContents' : ActorMethod<[], Array<Content>>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getAllRequests' : ActorMethod<[], Array<ContactRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[string], [] | [Character]>,
  'getContent' : ActorMethod<[string], [] | [Content]>,
  'getEpisode' : ActorMethod<[string], [] | [Episode]>,
  'getRequestsByStatus' : ActorMethod<[boolean], Array<ContactRequest>>,
  'getRequestsByTopic' : ActorMethod<[Topics], Array<ContactRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminRole' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRequest' : ActorMethod<[NewRequest], string>,
  'updateCharacter' : ActorMethod<[string, NewCharacter], undefined>,
  'updateContent' : ActorMethod<[string, NewContent], undefined>,
  'updateEpisode' : ActorMethod<[string, NewEpisode], undefined>,
  'updateRequestStatus' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];