/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NewCharacter = IDL.Record({
  'bio' : IDL.Text,
  'traits' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
  'power' : IDL.Text,
  'weapon' : IDL.Text,
});
export const NewContent = IDL.Record({
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'body' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const NewEpisode = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const Character = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'displayOrder' : IDL.Nat,
  'traits' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
  'imageUrl' : IDL.Text,
  'power' : IDL.Text,
  'weapon' : IDL.Text,
});
export const Content = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'contentType' : IDL.Text,
  'body' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Episode = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const Topics = IDL.Variant({
  'businessPartnerships' : IDL.Null,
  'interviewRequests' : IDL.Null,
  'publishingSubmissions' : IDL.Null,
  'eventOrWorkshopProposals' : IDL.Null,
  'advertisingInquiries' : IDL.Null,
  'challengesAndBounties' : IDL.Null,
  'generalInquiries' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactRequest = IDL.Record({
  'id' : IDL.Text,
  'topic' : Topics,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'processed' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const NewRequest = IDL.Record({
  'topic' : Topics,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacter' : IDL.Func([NewCharacter], [IDL.Text], []),
  'createContent' : IDL.Func([NewContent], [IDL.Text], []),
  'createEpisode' : IDL.Func([NewEpisode], [IDL.Text], []),
  'deleteCharacter' : IDL.Func([IDL.Text], [], []),
  'deleteContactRequest' : IDL.Func([IDL.Text], [], []),
  'deleteContent' : IDL.Func([IDL.Text], [], []),
  'deleteEpisode' : IDL.Func([IDL.Text], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllContents' : IDL.Func([], [IDL.Vec(Content)], ['query']),
  'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
  'getContent' : IDL.Func([IDL.Text], [IDL.Opt(Content)], ['query']),
  'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
  'getRequestsByStatus' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getRequestsByTopic' : IDL.Func(
      [Topics],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCharacters' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func([NewRequest], [IDL.Text], []),
  'updateCharacter' : IDL.Func([IDL.Text, NewCharacter], [], []),
  'updateContent' : IDL.Func([IDL.Text, NewContent], [], []),
  'updateEpisode' : IDL.Func([IDL.Text, NewEpisode], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NewCharacter = IDL.Record({
    'bio' : IDL.Text,
    'traits' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
    'power' : IDL.Text,
    'weapon' : IDL.Text,
  });
  const NewContent = IDL.Record({
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'body' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const NewEpisode = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const Character = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'displayOrder' : IDL.Nat,
    'traits' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
    'imageUrl' : IDL.Text,
    'power' : IDL.Text,
    'weapon' : IDL.Text,
  });
  const Content = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'contentType' : IDL.Text,
    'body' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Episode = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const Topics = IDL.Variant({
    'businessPartnerships' : IDL.Null,
    'interviewRequests' : IDL.Null,
    'publishingSubmissions' : IDL.Null,
    'eventOrWorkshopProposals' : IDL.Null,
    'advertisingInquiries' : IDL.Null,
    'challengesAndBounties' : IDL.Null,
    'generalInquiries' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactRequest = IDL.Record({
    'id' : IDL.Text,
    'topic' : Topics,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'processed' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const NewRequest = IDL.Record({
    'topic' : Topics,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacter' : IDL.Func([NewCharacter], [IDL.Text], []),
    'createContent' : IDL.Func([NewContent], [IDL.Text], []),
    'createEpisode' : IDL.Func([NewEpisode], [IDL.Text], []),
    'deleteCharacter' : IDL.Func([IDL.Text], [], []),
    'deleteContactRequest' : IDL.Func([IDL.Text], [], []),
    'deleteContent' : IDL.Func([IDL.Text], [], []),
    'deleteEpisode' : IDL.Func([IDL.Text], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllContents' : IDL.Func([], [IDL.Vec(Content)], ['query']),
    'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
    'getContent' : IDL.Func([IDL.Text], [IDL.Opt(Content)], ['query']),
    'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
    'getRequestsByStatus' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getRequestsByTopic' : IDL.Func(
        [Topics],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminRole' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCharacters' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func([NewRequest], [IDL.Text], []),
    'updateCharacter' : IDL.Func([IDL.Text, NewCharacter], [], []),
    'updateContent' : IDL.Func([IDL.Text, NewContent], [], []),
    'updateEpisode' : IDL.Func([IDL.Text, NewEpisode], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };